package ec.edu.puce.matchpoint.ui.components

import androidx.compose.foundation.layout.*
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.ui.*
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import ec.edu.puce.matchpoint.data.models.*
import ec.edu.puce.matchpoint.ui.UiState

fun SportType.label()="Básquet"
fun ReservationStatus.label()=if(this==ReservationStatus.CONFIRMED)"Confirmada" else "Cancelada"
fun TournamentStatus.label()=when(this){TournamentStatus.REGISTRATION->"Inscripciones abiertas";TournamentStatus.IN_PROGRESS->"En progreso";TournamentStatus.FINISHED->"Finalizado"}
fun MatchStatus.label()=when(this){MatchStatus.PENDING->"Pendiente";MatchStatus.READY->"Listo";MatchStatus.PLAYED->"Jugado"}
fun money(value:Double)=String.format(java.util.Locale.US,"$%.2f / hora",value)

@Composable fun StatusChip(text:String,positive:Boolean=true){Surface(color=if(positive)MaterialTheme.colorScheme.primaryContainer else MaterialTheme.colorScheme.surfaceVariant,shape=MaterialTheme.shapes.small){Text(text,Modifier.padding(horizontal=10.dp,vertical=5.dp),style=MaterialTheme.typography.labelMedium,color=if(positive)MaterialTheme.colorScheme.primary else MaterialTheme.colorScheme.onSurfaceVariant)}}
@Composable fun EmptyState(title:String,message:String,icon: @Composable () -> Unit={Icon(Icons.Default.SportsBasketball,null,Modifier.size(52.dp))},action:(()->Unit)?=null){Column(Modifier.fillMaxWidth().padding(40.dp),horizontalAlignment=Alignment.CenterHorizontally){icon();Spacer(Modifier.height(14.dp));Text(title,style=MaterialTheme.typography.titleLarge);Text(message,style=MaterialTheme.typography.bodyMedium,color=MaterialTheme.colorScheme.onSurfaceVariant);action?.let{TextButton(it){Text("Limpiar filtros")}}}}
@Composable fun LoadingState(){Box(Modifier.fillMaxSize(),contentAlignment=Alignment.Center){CircularProgressIndicator()}}
@Composable fun ErrorState(message:String,onRetry:(()->Unit)?=null){Column(Modifier.fillMaxWidth().padding(32.dp),horizontalAlignment=Alignment.CenterHorizontally){Icon(Icons.Default.CloudOff,null,tint=MaterialTheme.colorScheme.error);Text(message,Modifier.padding(vertical=12.dp),color=MaterialTheme.colorScheme.error);onRetry?.let{OutlinedButton(it){Text("Reintentar")}}}}
@Composable fun <T> StateView(state:UiState<T>,empty:(T)->Boolean={false},emptyContent: @Composable () -> Unit={EmptyState("Sin resultados","Todavía no hay información disponible.")},onRetry:(()->Unit)?=null,content: @Composable (T) -> Unit){when(state){UiState.Idle,UiState.Loading->LoadingState();is UiState.Error->ErrorState(state.message,onRetry);is UiState.Success->if(empty(state.data))emptyContent()else content(state.data)}}
@Composable fun PrimaryButton(text:String,onClick:()->Unit,enabled:Boolean=true,modifier:Modifier=Modifier){Button(onClick,modifier.fillMaxWidth().height(52.dp),enabled=enabled){Text(text)}}
@Composable fun ConfirmDialog(title:String,text:String,confirmText:String="Confirmar",onDismiss:()->Unit,onConfirm:()->Unit){AlertDialog(onDismissRequest=onDismiss,title={Text(title)},text={Text(text)},confirmButton={Button(onConfirm){Text(confirmText)}},dismissButton={TextButton(onDismiss){Text("Volver")}})}

@Composable fun CourtCard(c:CourtResponse,onClick:()->Unit,manager:Boolean=false,onEdit:(()->Unit)?=null){ElevatedCard(onClick=onClick,modifier=Modifier.fillMaxWidth().padding(vertical=7.dp)){Column(Modifier.padding(18.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text(c.name,style=MaterialTheme.typography.titleLarge,modifier=Modifier.weight(1f));StatusChip(if(c.active)"Activa" else "Inactiva",c.active)};Spacer(Modifier.height(10.dp));Text("📍 ${c.sector}   🏀 ${c.sportType.label()}");Text("Piso ${c.floorType} · Parqueadero: ${if(c.hasParking)"Sí" else "No"}",color=MaterialTheme.colorScheme.onSurfaceVariant);Text(money(c.pricePerHour),style=MaterialTheme.typography.titleMedium,color=MaterialTheme.colorScheme.primary,modifier=Modifier.padding(top=12.dp));if(manager&&onEdit!=null)TextButton(onEdit){Icon(Icons.Default.Edit,null);Text(" Editar") }else TextButton(onClick){Text("Ver disponibilidad")}}}}
@Composable fun ReservationCard(r:ReservationResponse,onClick:()->Unit){ElevatedCard(onClick=onClick,modifier=Modifier.fillMaxWidth().padding(vertical=7.dp)){Column(Modifier.padding(18.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text(r.courtName,style=MaterialTheme.typography.titleMedium);StatusChip(r.status.label(),r.status==ReservationStatus.CONFIRMED)};val dt=ec.edu.puce.matchpoint.utils.Formatters.dateTime(r.startsAt);Text("📅 ${dt.first}");Text("🕒 ${dt.second}   ⏱ ${r.durationMinutes} minutos");TextButton(onClick){Text("Ver detalle")}}}}
@Composable fun TournamentCard(t:TournamentResponse,onClick:()->Unit){ElevatedCard(onClick=onClick,modifier=Modifier.fillMaxWidth().padding(vertical=7.dp)){Column(Modifier.padding(18.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text("🏆 ${t.name}",style=MaterialTheme.typography.titleLarge,modifier=Modifier.weight(1f));StatusChip(t.status.label(),t.status!=TournamentStatus.FINISHED)};Text("🏀 ${t.sportType.label()}   👥 ${t.registeredTeams} / ${t.maxTeams} equipos");t.prize?.let{Text("Premio: $it")};TextButton(onClick){Text("Ver torneo")}}}}
@Composable fun TeamCard(team:TeamResponse,onClick:()->Unit){OutlinedCard(onClick=onClick,modifier=Modifier.fillMaxWidth().padding(vertical=5.dp)){Column(Modifier.padding(16.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text("🏀 ${team.name}",style=MaterialTheme.typography.titleMedium);StatusChip(if(team.stats.eliminated)"Eliminado" else "En competencia",!team.stats.eliminated)};Text("Responsable: ${team.contactName}");if(team.stats.matchesPlayed>0)Text("PJ ${team.stats.matchesPlayed}  ·  PG ${team.stats.matchesWon}  ·  PP ${team.stats.matchesLost}  ·  PF ${team.stats.pointsFor}  ·  PC ${team.stats.pointsAgainst}")}}}
@Composable fun MatchCard(match:MatchResponse,roundName:String,onManage:(()->Unit)?=null){OutlinedCard(Modifier.fillMaxWidth().padding(vertical=6.dp)){Column(Modifier.padding(16.dp),horizontalAlignment=Alignment.CenterHorizontally){Text(roundName.uppercase(),style=MaterialTheme.typography.labelLarge,color=MaterialTheme.colorScheme.primary);Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text(match.homeTeamName?:"Por definir");Text(match.homeScore?.toString()?:"–")};Text("VS",style=MaterialTheme.typography.labelSmall);Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text(match.awayTeamName?:"Por definir");Text(match.awayScore?.toString()?:"–")};match.scheduledAt?.let{val dt=ec.edu.puce.matchpoint.utils.Formatters.dateTime(it);Text("📅 ${dt.first} · 🕒 ${dt.second}")};StatusChip(match.status.label(),match.status==MatchStatus.PLAYED);onManage?.let{TextButton(it){Text(if(match.status==MatchStatus.PENDING)"Programar" else "Registrar resultado")}}}}}
