package ec.edu.puce.matchpoint.ui.screens

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.*
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.*
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.unit.dp
import ec.edu.puce.matchpoint.data.models.*
import ec.edu.puce.matchpoint.ui.UiState
import ec.edu.puce.matchpoint.ui.components.*
import ec.edu.puce.matchpoint.utils.Validators
import ec.edu.puce.matchpoint.viewmodel.*

@Composable fun LoginScreen(vm:AuthViewModel){var user by remember{mutableStateOf("")};var pass by remember{mutableStateOf("")};val state by vm.state.collectAsState();Column(Modifier.fillMaxSize().padding(28.dp),verticalArrangement=Arrangement.Center){Icon(Icons.Default.SportsBasketball,null,Modifier.size(72.dp),tint=MaterialTheme.colorScheme.primary);Text("MatchPoint",style=MaterialTheme.typography.headlineLarge);Text("Reserva. Compite. Gana.");Spacer(Modifier.height(28.dp));OutlinedTextField(user,{user=it},label={Text("Usuario Cognito")},modifier=Modifier.fillMaxWidth());Spacer(Modifier.height(12.dp));OutlinedTextField(pass,{pass=it},label={Text("Contraseña")},visualTransformation=PasswordVisualTransformation(),modifier=Modifier.fillMaxWidth());if(state is UiState.Error)Text((state as UiState.Error).message,color=MaterialTheme.colorScheme.error);Button({vm.login(user,pass)},Modifier.fillMaxWidth().padding(top=20.dp),enabled=state !is UiState.Loading){if(state is UiState.Loading)CircularProgressIndicator(Modifier.size(20.dp))else Text("Iniciar sesión")}}}

@Composable fun HomeScreen(role:UserRole,go:(String)->Unit){val options=if(role==UserRole.PLAYER)listOf("Canchas" to "courts","Mis reservas" to "reservations","Torneos" to "tournaments","Perfil" to "profile")else listOf("Mis canchas" to "courts","Torneos y partidos" to "tournaments","Perfil" to "profile");LazyColumn(Modifier.fillMaxSize().padding(16.dp)){item{Text("Hola, ${if(role==UserRole.PLAYER)"jugador" else "manager"}",style=MaterialTheme.typography.headlineMedium);Text("¿Qué quieres hacer hoy?");Spacer(Modifier.height(16.dp))};items(options){(label,route)->Card(onClick={go(route)},modifier=Modifier.fillMaxWidth().padding(vertical=6.dp)){Row(Modifier.padding(20.dp),verticalAlignment=Alignment.CenterVertically){Icon(Icons.Default.SportsBasketball,null);Spacer(Modifier.width(16.dp));Text(label,style=MaterialTheme.typography.titleMedium)}}}}}

@Composable fun CourtsScreen(vm:ContentViewModel,role:UserRole){val state by vm.courts.collectAsState();var sector by remember{mutableStateOf("")};var dialog by remember{mutableStateOf(false)};LaunchedEffect(Unit){vm.loadCourts()};Column(Modifier.fillMaxSize().padding(12.dp)){Row(verticalAlignment=Alignment.CenterVertically){OutlinedTextField(sector,{sector=it},label={Text("Sector")},modifier=Modifier.weight(1f));IconButton({vm.loadCourts(sector)}){Icon(Icons.Default.Search,"Buscar")}};if(role==UserRole.MANAGER)Button({dialog=true},Modifier.fillMaxWidth()){Text("Crear cancha")};StateView(state,{it.isEmpty()}){list->LazyColumn{items(list.filter{role==UserRole.PLAYER||it.managerUser.isNotBlank()}){c->Card(Modifier.fillMaxWidth().padding(vertical=5.dp)){Column(Modifier.padding(16.dp)){Text(c.name,style=MaterialTheme.typography.titleLarge);Text("${c.sector} · ${c.sportType} · $${c.pricePerHour}/hora");Text(if(c.active)"Disponible" else "Inactiva")}}}}}};if(dialog)CourtDialog({dialog=false}){vm.createCourt(it);dialog=false}}

@Composable private fun CourtDialog(close:()->Unit,save:(CreateCourtRequest)->Unit){var name by remember{mutableStateOf("")};var sector by remember{mutableStateOf("")};var floor by remember{mutableStateOf("")};var price by remember{mutableStateOf("")};var error by remember{mutableStateOf<String?>(null)};AlertDialog(onDismissRequest=close,title={Text("Nueva cancha")},text={Column{listOf("Nombre" to name,"Sector" to sector,"Tipo de piso" to floor,"Precio por hora" to price).forEachIndexed{i,(l,v)->OutlinedTextField(v,{n->when(i){0->name=n;1->sector=n;2->floor=n;else->price=n}},label={Text(l)})};error?.let{Text(it,color=MaterialTheme.colorScheme.error)}}},confirmButton={TextButton({error=Validators.court(name,sector,floor,price.toDoubleOrNull());if(error==null)save(CreateCourtRequest(name,sector,true,SportType.BASKET,floor,price.toDouble()))}){Text("Guardar")}},dismissButton={TextButton(close){Text("Cancelar")}})}

@Composable fun ReservationsScreen(vm:ContentViewModel){val state by vm.reservations.collectAsState();var dialog by remember{mutableStateOf(false)};LaunchedEffect(Unit){vm.loadReservations()};Column(Modifier.fillMaxSize().padding(12.dp)){Button({dialog=true},Modifier.fillMaxWidth()){Text("Crear reserva")};StateView(state,{it.isEmpty()}){list->LazyColumn{items(list){r->Card(Modifier.fillMaxWidth().padding(vertical=5.dp)){Column(Modifier.padding(16.dp)){Text(r.courtName,style=MaterialTheme.typography.titleMedium);Text("${r.startsAt.replace('T',' ')} · ${r.durationMinutes} min");Text(r.status.name);if(r.status==ReservationStatus.CONFIRMED)TextButton({vm.cancel(r.id)}){Text("Cancelar reserva")}}}}}}};if(dialog)ReservationDialog({dialog=false}){vm.reserve(it);dialog=false}}
@Composable private fun ReservationDialog(close:()->Unit,save:(CreateReservationRequest)->Unit){var court by remember{mutableStateOf("")};var date by remember{mutableStateOf("")};var duration by remember{mutableStateOf("60")};var error by remember{mutableStateOf<String?>(null)};AlertDialog(onDismissRequest=close,title={Text("Reservar cancha")},text={Column{OutlinedTextField(court,{court=it},label={Text("ID cancha")});OutlinedTextField(date,{date=it},label={Text("Fecha ISO: 2026-08-20T18:00:00")});OutlinedTextField(duration,{duration=it},label={Text("Duración (minutos)")});error?.let{Text(it,color=MaterialTheme.colorScheme.error)}}},confirmButton={TextButton({error=Validators.reservation(court.toLongOrNull(),date,duration.toIntOrNull());if(error==null)save(CreateReservationRequest(court.toLong(),date,duration.toInt()))}){Text("Reservar")}},dismissButton={TextButton(close){Text("Cancelar")}})}

@Composable fun TournamentsScreen(vm:ContentViewModel,role:UserRole){val state by vm.tournaments.collectAsState();val detail by vm.tournamentDetail.collectAsState();var create by remember{mutableStateOf(false)};var teamFor by remember{mutableStateOf<Long?>(null)};var detailId by remember{mutableStateOf<Long?>(null)};var editMatch by remember{mutableStateOf<MatchResponse?>(null)};LaunchedEffect(Unit){vm.loadTournaments()};Column(Modifier.fillMaxSize().padding(12.dp)){if(role==UserRole.MANAGER)Button({create=true},Modifier.fillMaxWidth()){Text("Crear torneo")};StateView(state,{it.isEmpty()}){list->LazyColumn{items(list){t->Card(Modifier.fillMaxWidth().padding(vertical=5.dp)){Column(Modifier.padding(16.dp)){Text(t.name,style=MaterialTheme.typography.titleLarge);Text("${t.registeredTeams}/${t.maxTeams} equipos · ${t.status}");t.championTeamName?.let{Text("Campeón: $it")};TextButton({detailId=t.id;vm.loadTournament(t.id)}){Text("Ver cuadro y partidos")};if(role==UserRole.PLAYER&&t.status==TournamentStatus.REGISTRATION)TextButton({teamFor=t.id}){Text("Inscribir equipo")};if(role==UserRole.MANAGER&&t.status==TournamentStatus.REGISTRATION)TextButton({vm.startTournament(t.id)}){Text("Iniciar torneo")}}}}}}};if(create)TournamentDialog({create=false}){vm.createTournament(it);create=false};teamFor?.let{id->TeamDialog({teamFor=null}){vm.registerTeam(id,it);teamFor=null}};if(detailId!=null)TournamentDetailDialog(detail,role,{detailId=null},{editMatch=it});editMatch?.let{m->MatchEditDialog(m,{editMatch=null}){date,home,away->val tournamentId=detailId?:m.tournamentId;if(date!=null)vm.scheduleMatch(tournamentId,m.id,date)else vm.scoreMatch(tournamentId,m.id,home!!,away!!);editMatch=null}}}

@Composable private fun TournamentDetailDialog(state:UiState<TournamentProgressResponse>,role:UserRole,close:()->Unit,edit:(MatchResponse)->Unit){AlertDialog(onDismissRequest=close,title={Text("Cuadro del torneo")},text={StateView(state){progress->LazyColumn(Modifier.heightIn(max=520.dp)){progress.rounds.forEach{round->item{Text(round.roundName,style=MaterialTheme.typography.titleMedium)};items(round.matches){m->Card(Modifier.fillMaxWidth().padding(vertical=4.dp)){Column(Modifier.padding(10.dp)){Text("${m.homeTeamName?:"Por definir"}  VS  ${m.awayTeamName?:"Por definir"}");Text("Marcador: ${m.homeScore?:"-"} - ${m.awayScore?:"-"}");Text("${m.status} · ${m.scheduledAt?:"Sin programar"}");m.winnerTeamName?.let{Text("Ganador: $it")};if(role==UserRole.MANAGER&&m.status!=MatchStatus.PLAYED)TextButton({edit(m)}){Text(if(m.status==MatchStatus.PENDING)"Programar" else "Registrar marcador")}}}}}}}},confirmButton={TextButton(close){Text("Cerrar")}})}

@Composable private fun MatchEditDialog(match:MatchResponse,close:()->Unit,save:(String?,Int?,Int?)->Unit){var date by remember{mutableStateOf(match.scheduledAt?:"")};var home by remember{mutableStateOf("")};var away by remember{mutableStateOf("")};var error by remember{mutableStateOf<String?>(null)};val scheduling=match.status==MatchStatus.PENDING;AlertDialog(onDismissRequest=close,title={Text(if(scheduling)"Programar partido" else "Registrar marcador")},text={Column{if(scheduling)OutlinedTextField(date,{date=it},label={Text("Fecha ISO")})else{OutlinedTextField(home,{home=it},label={Text(match.homeTeamName?:"Local")});OutlinedTextField(away,{away=it},label={Text(match.awayTeamName?:"Visitante")})};error?.let{Text(it,color=MaterialTheme.colorScheme.error)}}},confirmButton={TextButton({if(scheduling){error=if(runCatching{java.time.LocalDateTime.parse(date)}.getOrNull()?.isAfter(java.time.LocalDateTime.now())==true)null else "Selecciona una fecha futura.";if(error==null)save(date,null,null)}else{error=Validators.score(home.toIntOrNull(),away.toIntOrNull());if(error==null)save(null,home.toInt(),away.toInt())}}){Text("Guardar")}},dismissButton={TextButton(close){Text("Cancelar")}})}
@Composable private fun TournamentDialog(close:()->Unit,save:(CreateTournamentRequest)->Unit){var name by remember{mutableStateOf("")};var teams by remember{mutableStateOf("4")};var prize by remember{mutableStateOf("")};var error by remember{mutableStateOf<String?>(null)};AlertDialog(onDismissRequest=close,title={Text("Nuevo torneo")},text={Column{OutlinedTextField(name,{name=it},label={Text("Nombre")});OutlinedTextField(teams,{teams=it},label={Text("Cupos")});OutlinedTextField(prize,{prize=it},label={Text("Premio (opcional)")});error?.let{Text(it,color=MaterialTheme.colorScheme.error)}}},confirmButton={TextButton({error=Validators.tournament(name,teams.toIntOrNull());if(error==null)save(CreateTournamentRequest(name,SportType.BASKET,teams.toInt(),prize.ifBlank{null}))}){Text("Crear")}},dismissButton={TextButton(close){Text("Cancelar")}})}
@Composable private fun TeamDialog(close:()->Unit,save:(RegisterTeamRequest)->Unit){var n by remember{mutableStateOf("")};var c by remember{mutableStateOf("")};var e by remember{mutableStateOf("")};var p by remember{mutableStateOf("")};var error by remember{mutableStateOf<String?>(null)};AlertDialog(onDismissRequest=close,title={Text("Inscribir equipo")},text={Column{listOf("Equipo" to n,"Contacto" to c,"Correo" to e,"Teléfono" to p).forEachIndexed{i,(l,v)->OutlinedTextField(v,{x->when(i){0->n=x;1->c=x;2->e=x;else->p=x}},label={Text(l)})};error?.let{Text(it,color=MaterialTheme.colorScheme.error)}}},confirmButton={TextButton({error=Validators.team(n,c,e,p);if(error==null)save(RegisterTeamRequest(n,c,e,p))}){Text("Inscribir")}},dismissButton={TextButton(close){Text("Cancelar")}})}

@Composable fun ProfileScreen(vm:ContentViewModel){val state by vm.profile.collectAsState();var edit by remember{mutableStateOf(false)};LaunchedEffect(Unit){vm.loadProfile()};Box(Modifier.fillMaxSize().padding(16.dp)){StateView(state){p->Column{Text(p.name,style=MaterialTheme.typography.headlineMedium);Text(p.email?:"Sin correo");Text(p.phone?:"Sin teléfono");Text("Usuario: ${p.username}");Button({edit=true},Modifier.padding(top=20.dp)){Text("Editar perfil")};if(edit)ProfileDialog(p,{edit=false}){vm.saveProfile(it,false);edit=false}}}}}
@Composable private fun ProfileDialog(p:UserResponse,close:()->Unit,save:(UserRequest)->Unit){var n by remember{mutableStateOf(p.name)};var e by remember{mutableStateOf(p.email?:"")};var ph by remember{mutableStateOf(p.phone?:"")};var error by remember{mutableStateOf<String?>(null)};AlertDialog(onDismissRequest=close,title={Text("Editar perfil")},text={Column{OutlinedTextField(n,{n=it},label={Text("Nombre")});OutlinedTextField(e,{e=it},label={Text("Correo")});OutlinedTextField(ph,{ph=it},label={Text("Teléfono")});error?.let{Text(it,color=MaterialTheme.colorScheme.error)}}},confirmButton={TextButton({error=Validators.profile(n,e,ph);if(error==null)save(UserRequest(n,e.ifBlank{null},ph.ifBlank{null}))}){Text("Guardar")}},dismissButton={TextButton(close){Text("Cancelar")}})}
