package ec.edu.puce.matchpoint.ui.screens

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.clickable
import androidx.compose.foundation.lazy.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.*
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.unit.dp
import ec.edu.puce.matchpoint.data.models.*
import ec.edu.puce.matchpoint.ui.UiState
import ec.edu.puce.matchpoint.ui.components.*
import ec.edu.puce.matchpoint.utils.Formatters
import ec.edu.puce.matchpoint.utils.Validators
import ec.edu.puce.matchpoint.viewmodel.*
import java.time.*
import java.time.format.DateTimeFormatter

@Composable fun LoginScreen(vm:AuthViewModel){var user by remember{mutableStateOf("")};var pass by remember{mutableStateOf("")};val state by vm.state.collectAsState();Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(28.dp),verticalArrangement=Arrangement.Center,horizontalAlignment=Alignment.CenterHorizontally){Surface(color=MaterialTheme.colorScheme.primaryContainer,shape=MaterialTheme.shapes.large){Icon(Icons.Default.SportsBasketball,null,Modifier.padding(22.dp).size(64.dp),tint=MaterialTheme.colorScheme.primary)};Spacer(Modifier.height(18.dp));Text("MatchPoint",style=MaterialTheme.typography.displaySmall);Text("Reserva. Compite. Gana.",color=MaterialTheme.colorScheme.onSurfaceVariant);Spacer(Modifier.height(32.dp));OutlinedTextField(user,{user=it},label={Text("Usuario")},leadingIcon={Icon(Icons.Default.Person,null)},singleLine=true,modifier=Modifier.fillMaxWidth());Spacer(Modifier.height(12.dp));OutlinedTextField(pass,{pass=it},label={Text("Contraseña")},leadingIcon={Icon(Icons.Default.Lock,null)},visualTransformation=PasswordVisualTransformation(),singleLine=true,modifier=Modifier.fillMaxWidth());if(state is UiState.Error)Text((state as UiState.Error).message,color=MaterialTheme.colorScheme.error,modifier=Modifier.padding(top=10.dp));PrimaryButton("Iniciar sesión",{vm.login(user,pass)},state !is UiState.Loading,Modifier.padding(top=22.dp))}}

@Composable fun HomeScreen(vm:ContentViewModel,role:UserRole,username:String?,go:(String)->Unit){val profile by vm.profile.collectAsState();val courts by vm.courts.collectAsState();val reservations by vm.reservations.collectAsState();val tournaments by vm.tournaments.collectAsState();LaunchedEffect(Unit){vm.loadProfile();vm.loadCourts();vm.loadTournaments();if(role==UserRole.PLAYER)vm.loadReservations()};val name=(profile as? UiState.Success)?.data?.name?.substringBefore(' ')?:username?:if(role==UserRole.PLAYER)"Jugador" else "Manager";LazyColumn(Modifier.fillMaxSize(),contentPadding=PaddingValues(18.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{Text("Hola, $name 👋",style=MaterialTheme.typography.headlineMedium);Text(if(role==UserRole.PLAYER)"¿Dónde quieres jugar hoy?" else "Panel de gestión",color=MaterialTheme.colorScheme.onSurfaceVariant)};item{Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(10.dp)){QuickAction("Canchas",Icons.Default.SportsBasketball,Modifier.weight(1f)){go("courts")};if(role==UserRole.PLAYER)QuickAction("Reservas",Icons.Default.Event,Modifier.weight(1f)){go("reservations")}else QuickAction("Torneos",Icons.Default.EmojiEvents,Modifier.weight(1f)){go("tournaments")}}};if(role==UserRole.PLAYER){val next=(reservations as? UiState.Success)?.data?.filter{it.status==ReservationStatus.CONFIRMED&&runCatching{LocalDateTime.parse(it.startsAt).isAfter(LocalDateTime.now())}.getOrDefault(false)}?.minByOrNull{it.startsAt};next?.let{item{SectionTitle("Próxima reserva","Ver todas"){go("reservations")};ReservationCard(it){go("reservations")}}};val available=(tournaments as?UiState.Success)?.data?.filter{it.status==TournamentStatus.REGISTRATION}?.take(2).orEmpty();if(available.isNotEmpty()){item{SectionTitle("Torneos disponibles","Ver todos"){go("tournaments")}};items(available){TournamentCard(it){go("tournaments")}}}}else{val mineCourts=(courts as?UiState.Success)?.data?.count{it.managerUser==username}?:0;val mineTournaments=(tournaments as?UiState.Success)?.data?.count{it.managerUser==username}?:0;item{Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(12.dp)){Metric("Canchas",mineCourts,Modifier.weight(1f));Metric("Torneos",mineTournaments,Modifier.weight(1f))}};item{PrimaryButton("Crear cancha",{go("courts")});Spacer(Modifier.height(8.dp));OutlinedButton({go("tournaments")},Modifier.fillMaxWidth()){Text("Crear torneo")}}}}}
@Composable private fun QuickAction(label:String,icon:androidx.compose.ui.graphics.vector.ImageVector,modifier:Modifier,onClick:()->Unit){ElevatedCard(onClick=onClick,modifier=modifier){Column(Modifier.fillMaxWidth().padding(vertical=20.dp),horizontalAlignment=Alignment.CenterHorizontally){Icon(icon,null,Modifier.size(34.dp),tint=MaterialTheme.colorScheme.primary);Text(label,style=MaterialTheme.typography.titleMedium)}}}
@Composable private fun Metric(label:String,value:Int,modifier:Modifier){Card(modifier=modifier){Column(Modifier.padding(18.dp)){Text(value.toString(),style=MaterialTheme.typography.displaySmall,color=MaterialTheme.colorScheme.primary);Text(label)}}}
@Composable private fun SectionTitle(title:String,action:String,onClick:()->Unit){Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically,horizontalArrangement=Arrangement.SpaceBetween){Text(title,style=MaterialTheme.typography.titleLarge);TextButton(onClick){Text(action)}}}

@Composable fun CourtsScreen(vm:ContentViewModel,role:UserRole,username:String?) {
    val state by vm.courts.collectAsState()
    var query by remember { mutableStateOf("") }; var sector by remember { mutableStateOf("") }
    var selected by remember { mutableStateOf<CourtResponse?>(null) }; var create by remember { mutableStateOf(false) }
    var edit by remember { mutableStateOf<CourtResponse?>(null) }; var reserve by remember { mutableStateOf<CourtResponse?>(null) }
    LaunchedEffect(Unit) { vm.loadCourts() }
    Box(Modifier.fillMaxSize()) {
        Column(Modifier.fillMaxSize().padding(horizontal=16.dp)) {
            Text(if(role==UserRole.PLAYER) "Buscar canchas" else "Mis canchas",style=MaterialTheme.typography.headlineMedium,modifier=Modifier.padding(vertical=12.dp))
            OutlinedTextField(query,{query=it},label={Text("Buscar por nombre")},leadingIcon={Icon(Icons.Default.Search,null)},singleLine=true,modifier=Modifier.fillMaxWidth())
            OutlinedTextField(sector,{sector=it},label={Text("Sector")},singleLine=true,modifier=Modifier.fillMaxWidth().padding(top=8.dp))
            StateView(state=state,empty={it.isEmpty()},emptyContent={EmptyState("No encontramos canchas","Prueba cambiando los filtros.",action={query="";sector=""})},onRetry={vm.loadCourts()}) { all ->
                val list=all.filter{c->(role==UserRole.PLAYER||c.managerUser==username)&&c.name.contains(query,true)&&c.sector.contains(sector,true)}
                if(list.isEmpty()) EmptyState("No encontramos canchas","Prueba cambiando los filtros.",action={query="";sector=""})
                else LazyColumn(contentPadding=PaddingValues(bottom=90.dp)){items(list,key={it.id}){c->CourtCard(c,{selected=c},role==UserRole.MANAGER){edit=c}}}
            }
        }
        if(role==UserRole.MANAGER) FloatingActionButton({create=true},Modifier.align(Alignment.BottomEnd).padding(20.dp)){Icon(Icons.Default.Add,"Crear cancha")}
    }
    selected?.let { court -> CourtDetailDialog(court,role,{selected=null},{reserve=court;selected=null}) }
    if(create) CourtFormDialog(null,{create=false}){vm.createCourt(it);create=false}
    edit?.let { court -> CourtEditDialog(court,{edit=null}){request,active->vm.updateCourt(court.id,request,active);edit=null} }
    reserve?.let { court -> ReservationFormDialog(court,{reserve=null}){vm.reserve(it);reserve=null} }
}
@Composable private fun CourtDetailDialog(c:CourtResponse,role:UserRole,close:()->Unit,reserve:(CourtResponse)->Unit){AlertDialog(onDismissRequest=close,title={Text(c.name)},text={Column(Modifier.verticalScroll(rememberScrollState()),verticalArrangement=Arrangement.spacedBy(10.dp)){StatusChip(if(c.active)"Disponible" else "No disponible",c.active);InfoLine("Sector",c.sector);InfoLine("Deporte",c.sportType.label());InfoLine("Piso",c.floorType);InfoLine("Parqueadero",if(c.hasParking)"Sí" else "No");InfoLine("Precio",money(c.pricePerHour));HorizontalDivider();Text("Disponibilidad",style=MaterialTheme.typography.titleMedium);Text(if(c.active)"Consulta una fecha y hora para reservar." else "Cancha no disponible actualmente")}},confirmButton={if(role==UserRole.PLAYER&&c.active)Button({reserve(c)}){Text("Reservar cancha")}else TextButton(close){Text("Cerrar")}},dismissButton={if(role==UserRole.PLAYER&&c.active)TextButton(close){Text("Volver")}})}
@Composable private fun InfoLine(label:String,value:String){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text(label,color=MaterialTheme.colorScheme.onSurfaceVariant);Text(value,style=MaterialTheme.typography.bodyLarge)}}
@Composable private fun CourtFormDialog(existing:CourtResponse?,close:()->Unit,save:(CreateCourtRequest)->Unit){var name by remember{mutableStateOf(existing?.name?:"")};var sector by remember{mutableStateOf(existing?.sector?:"")};var floor by remember{mutableStateOf(existing?.floorType?:"")};var price by remember{mutableStateOf(existing?.pricePerHour?.toString()?:"")};var parking by remember{mutableStateOf(existing?.hasParking?:false)};var error by remember{mutableStateOf<String?>(null)};AlertDialog(onDismissRequest=close,title={Text("Nueva cancha")},text={Column(Modifier.verticalScroll(rememberScrollState())){Field(name,{name=it},"Nombre",error?.takeIf{name.isBlank()});Field(sector,{sector=it},"Sector",error?.takeIf{sector.isBlank()});Field(floor,{floor=it},"Tipo de piso",error?.takeIf{floor.isBlank()});Field(price,{price=it},"Precio por hora",error?.takeIf{price.toDoubleOrNull()?.let{it<=0}!=false});Row(verticalAlignment=Alignment.CenterVertically){Text("Parqueadero",Modifier.weight(1f));Switch(parking,{parking=it})};Text("Deporte: Básquet",color=MaterialTheme.colorScheme.onSurfaceVariant)}},confirmButton={Button({error=Validators.court(name,sector,floor,price.toDoubleOrNull());if(error==null)save(CreateCourtRequest(name.trim(),sector.trim(),parking,SportType.BASKET,floor.trim(),price.toDouble()))}){Text("Crear cancha")}},dismissButton={TextButton(close){Text("Cancelar")}})}
@Composable private fun CourtEditDialog(c:CourtResponse,close:()->Unit,save:(UpdateCourtRequest,Boolean)->Unit){var price by remember{mutableStateOf(c.pricePerHour.toString())};var active by remember{mutableStateOf(c.active)};var error by remember{mutableStateOf<String?>(null)};AlertDialog(onDismissRequest=close,title={Text("Editar cancha")},text={Column{Text(c.name,style=MaterialTheme.typography.titleMedium);Text("El backend solo permite editar precio y estado.",style=MaterialTheme.typography.bodySmall);Field(price,{price=it},"Precio por hora",error);Row(verticalAlignment=Alignment.CenterVertically){Text("Cancha activa",Modifier.weight(1f));Switch(active,{active=it})}}},confirmButton={Button({if(price.toDoubleOrNull()?.let{it>0}!=true)error="El precio debe ser mayor que 0." else save(UpdateCourtRequest(price.toDouble(),active),active)}){Text("Guardar cambios")}},dismissButton={TextButton(close){Text("Cancelar")}})}
@Composable private fun Field(value:String,onValue:(String)->Unit,label:String,error:String?=null){OutlinedTextField(value,onValue,label={Text(label)},isError=error!=null,supportingText=error?.let{{Text(it)}},singleLine=true,modifier=Modifier.fillMaxWidth().padding(vertical=3.dp))}

@Composable fun ReservationsScreen(vm:ContentViewModel){val state by vm.reservations.collectAsState();val courts by vm.courts.collectAsState();var filter by remember{mutableStateOf("Todas")};var selected by remember{mutableStateOf<ReservationResponse?>(null)};var cancel by remember{mutableStateOf<ReservationResponse?>(null)};var chooseCourt by remember{mutableStateOf(false)};LaunchedEffect(Unit){vm.loadReservations();vm.loadCourts()};Column(Modifier.fillMaxSize().padding(horizontal=16.dp)){Text("Mis reservas",style=MaterialTheme.typography.headlineMedium,modifier=Modifier.padding(vertical=12.dp));Row(horizontalArrangement=Arrangement.spacedBy(6.dp)){listOf("Todas","Próximas","Canceladas").forEach{FilterChip(filter==it,{filter=it},{Text(it)})}};StateView(state,{it.isEmpty()},{EmptyState("No tienes reservas","Busca una cancha y crea tu primera reserva.")},{vm.loadReservations()}){all->val now=LocalDateTime.now();val list=all.filter{when(filter){"Próximas"->it.status==ReservationStatus.CONFIRMED&&runCatching{LocalDateTime.parse(it.startsAt).isAfter(now)}.getOrDefault(false);"Canceladas"->it.status==ReservationStatus.CANCELLED;else->true}};if(list.isEmpty())EmptyState("Sin reservas en esta categoría","Selecciona otro filtro.")else LazyColumn(contentPadding=PaddingValues(bottom=90.dp)){items(list,key={it.id}){r->ReservationCard(r){selected=r}}}};FloatingActionButton({chooseCourt=true},Modifier.align(Alignment.End)){Icon(Icons.Default.Add,"Crear reserva")}};selected?.let{ReservationDetailDialog(it,{selected=null}){cancel=it;selected=null}};cancel?.let{ConfirmDialog("¿Cancelar reserva?","Esta acción cancelará tu reserva.","Sí, cancelar",{cancel=null}){vm.cancel(it.id);cancel=null}};if(chooseCourt){val list=(courts as?UiState.Success)?.data?.filter{it.active}.orEmpty();CourtPickerDialog(list,{chooseCourt=false}){selectedCourt->chooseCourt=false;vm.pendingCourt.value=selectedCourt}};vm.pendingCourt.collectAsState().value?.let{court->ReservationFormDialog(court,{vm.pendingCourt.value=null}){vm.reserve(it);vm.pendingCourt.value=null}}}
@Composable private fun CourtPickerDialog(courts:List<CourtResponse>,close:()->Unit,pick:(CourtResponse)->Unit){AlertDialog(onDismissRequest=close,title={Text("Selecciona una cancha")},text={LazyColumn(Modifier.heightIn(max=420.dp)){items(courts){c->ListItem(headlineContent={Text(c.name)},supportingContent={Text("${c.sector} · ${money(c.pricePerHour)}")},modifier=Modifier.fillMaxWidth().clickable{pick(c)});HorizontalDivider()}}},confirmButton={TextButton(close){Text("Cerrar")}})}
@Composable private fun ReservationDetailDialog(r:ReservationResponse,close:()->Unit,cancel:(ReservationResponse)->Unit){val dt=Formatters.dateTime(r.startsAt);AlertDialog(onDismissRequest=close,title={Text("Reserva")},text={Column(verticalArrangement=Arrangement.spacedBy(10.dp)){Text(r.courtName,style=MaterialTheme.typography.headlineSmall);InfoLine("Fecha",dt.first);InfoLine("Hora",dt.second);InfoLine("Duración","${r.durationMinutes} minutos");InfoLine("Estado",r.status.label())}},confirmButton={if(r.status==ReservationStatus.CONFIRMED)Button({cancel(r)},colors=ButtonDefaults.buttonColors(containerColor=MaterialTheme.colorScheme.error)){Text("Cancelar reserva")}else TextButton(close){Text("Cerrar")}},dismissButton={if(r.status==ReservationStatus.CONFIRMED)TextButton(close){Text("Volver")}})}

@OptIn(ExperimentalMaterial3Api::class)
@Composable private fun ReservationFormDialog(court:CourtResponse,close:()->Unit,save:(CreateReservationRequest)->Unit) {
    var date by remember { mutableStateOf<LocalDate?>(null) }; var time by remember { mutableStateOf<LocalTime?>(null) }
    var duration by remember { mutableIntStateOf(60) }; var showDate by remember { mutableStateOf(false) }; var showTime by remember { mutableStateOf(false) }
    val starts=if(date!=null&&time!=null) LocalDateTime.of(date,time).withSecond(0).withNano(0) else null
    AlertDialog(onDismissRequest=close,title={Text("Reservar cancha")},text={
        Column(Modifier.verticalScroll(rememberScrollState()),verticalArrangement=Arrangement.spacedBy(12.dp)){
            Text(court.name,style=MaterialTheme.typography.titleLarge);Text(money(court.pricePerHour),color=MaterialTheme.colorScheme.primary)
            OutlinedButton({showDate=true},Modifier.fillMaxWidth()){Icon(Icons.Default.DateRange,null);Text(" ${date?.format(DateTimeFormatter.ofPattern("d MMM yyyy"))?:"Seleccionar fecha"}")}
            OutlinedButton({showTime=true},Modifier.fillMaxWidth()){Icon(Icons.Default.Schedule,null);Text(" ${time?.format(DateTimeFormatter.ofPattern("HH:mm"))?:"Seleccionar hora"}")}
            Text("Duración"); val durations=listOf(60,90,120)
            SingleChoiceSegmentedButtonRow { durations.forEachIndexed { i,d -> SegmentedButton(selected=duration==d,onClick={duration=d},shape=SegmentedButtonDefaults.itemShape(i,durations.size)){Text("$d min")} } }
            HorizontalDivider();Text("Resumen",style=MaterialTheme.typography.titleMedium);Text("Fecha: ${date?:"Pendiente"}\nHora: ${time?:"Pendiente"}\nDuración: $duration minutos")
        }
    },confirmButton={Button({starts?.let{save(CreateReservationRequest(court.id,it.toString(),duration))}},enabled=starts?.isAfter(LocalDateTime.now())==true){Text("Confirmar reserva")}},dismissButton={TextButton(close){Text("Cancelar")}})
    if(showDate) DatePickerModal({showDate=false}){date=it}; if(showTime) TimePickerModal({showTime=false}){time=it}
}

@OptIn(ExperimentalMaterial3Api::class) @Composable private fun DatePickerModal(close:()->Unit,pick:(LocalDate)->Unit){val state=rememberDatePickerState(initialSelectedDateMillis=System.currentTimeMillis());DatePickerDialog(onDismissRequest=close,confirmButton={Button({state.selectedDateMillis?.let{pick(Instant.ofEpochMilli(it).atZone(ZoneOffset.UTC).toLocalDate())};close()}){Text("Aceptar")}}){DatePicker(state)}}
@OptIn(ExperimentalMaterial3Api::class) @Composable private fun TimePickerModal(close:()->Unit,pick:(LocalTime)->Unit){val now=LocalTime.now();val state=rememberTimePickerState(now.hour,now.minute,true);AlertDialog(onDismissRequest=close,text={TimePicker(state)},confirmButton={Button({pick(LocalTime.of(state.hour,state.minute));close()}){Text("Aceptar")}},dismissButton={TextButton(close){Text("Cancelar")}})}

@Composable fun TournamentsScreen(vm:ContentViewModel,role:UserRole,username:String?) {
    val state by vm.tournaments.collectAsState(); var filter by remember { mutableStateOf<TournamentStatus?>(null) }
    var selected by remember { mutableStateOf<Long?>(null) }; var create by remember { mutableStateOf(false) }
    LaunchedEffect(Unit){vm.loadTournaments()}
    Box(Modifier.fillMaxSize()) {
        Column(Modifier.fillMaxSize().padding(horizontal=16.dp)) {
            Text(if(role==UserRole.MANAGER)"Mis torneos" else "Torneos",style=MaterialTheme.typography.headlineMedium,modifier=Modifier.padding(vertical=12.dp))
            LazyRow(horizontalArrangement=Arrangement.spacedBy(6.dp)){item{FilterChip(filter==null,{filter=null},{Text("Todos")})};items(TournamentStatus.entries){s->FilterChip(filter==s,{filter=s},{Text(s.label())})}}
            StateView(state=state,empty={it.isEmpty()},emptyContent={EmptyState("No hay torneos","Vuelve pronto para descubrir nuevas competencias.")},onRetry={vm.loadTournaments()}) { all ->
                val list=all.filter{(role==UserRole.PLAYER||it.managerUser==username)&&(filter==null||it.status==filter)}
                if(list.isEmpty()) EmptyState("Sin torneos en esta categoría","Selecciona otro filtro.")
                else LazyColumn(contentPadding=PaddingValues(bottom=90.dp)){items(list,key={it.id}){t->TournamentCard(t){selected=t.id;vm.loadTournament(t.id);vm.loadTeams(t.id)}}}
            }
        }
        if(role==UserRole.MANAGER) FloatingActionButton({create=true},Modifier.align(Alignment.BottomEnd).padding(20.dp)){Icon(Icons.Default.Add,"Crear torneo")}
    }
    selected?.let{id->TournamentDetailDialog(vm,id,role,{selected=null})}
    if(create) TournamentFormDialog({create=false}){vm.createTournament(it);create=false}
}
@Composable private fun TournamentDetailDialog(vm:ContentViewModel,id:Long,role:UserRole,close:()->Unit) {
    val state by vm.tournamentDetail.collectAsState(); val teams by vm.teams.collectAsState()
    var tab by remember { mutableIntStateOf(0) }; var register by remember { mutableStateOf(false) }
    var teamDetail by remember { mutableStateOf<TeamResponse?>(null) }; var manage by remember { mutableStateOf<MatchResponse?>(null) }; var confirmStart by remember { mutableStateOf(false) }
    AlertDialog(onDismissRequest=close,title={Text((state as?UiState.Success)?.data?.tournament?.name?:"Torneo")},text={
        StateView(state=state,onRetry={vm.loadTournament(id)}) { progress ->
            val tournament=progress.tournament
            Column(Modifier.heightIn(max=590.dp)) {
                Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){StatusChip(tournament.status.label());Text("${tournament.registeredTeams}/${tournament.maxTeams} equipos")}
                tournament.prize?.let{Text("Premio: $it")};tournament.courtName?.let{Text("Cancha: $it")}
                if(tournament.status==TournamentStatus.FINISHED&&tournament.championTeamName!=null) Card(Modifier.fillMaxWidth().padding(vertical=10.dp),colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.secondaryContainer)){Column(Modifier.fillMaxWidth().padding(16.dp),horizontalAlignment=Alignment.CenterHorizontally){Text("🏆 CAMPEÓN");Text(tournament.championTeamName,style=MaterialTheme.typography.headlineSmall)}}
                TabRow(tab){listOf("Resumen","Equipos","Cuadro").forEachIndexed{i,label->Tab(tab==i,{tab=i},text={Text(label)})}}
                when(tab) {
                    0 -> Column(Modifier.padding(top=12.dp)) {
                        InfoLine("Deporte",tournament.sportType.label());InfoLine("Estado",tournament.status.label())
                        if(role==UserRole.PLAYER&&tournament.status==TournamentStatus.REGISTRATION) PrimaryButton("Inscribir equipo",{register=true},modifier=Modifier.padding(top=12.dp))
                        if(role==UserRole.MANAGER&&tournament.status==TournamentStatus.REGISTRATION){val ready=tournament.registeredTeams==tournament.maxTeams;Text(if(ready)"El torneo está listo para iniciar." else "Faltan ${tournament.maxTeams-tournament.registeredTeams} equipos para iniciar.",Modifier.padding(top=12.dp));PrimaryButton("Iniciar torneo",{confirmStart=true},ready,Modifier.padding(top=8.dp))}
                    }
                    1 -> StateView(state=teams,empty={it.isEmpty()},emptyContent={EmptyState("Sin equipos","Aún no hay equipos inscritos.")}) { list -> LazyColumn { items(list){team->TeamCard(team){teamDetail=team}} } }
                    else -> LazyColumn { progress.rounds.forEach { round -> item { Text(round.roundName,style=MaterialTheme.typography.titleLarge,modifier=Modifier.padding(top=12.dp)) }; items(round.matches.sortedBy{it.positionInRound}) { match -> MatchCard(match,round.roundName,if(role==UserRole.MANAGER&&match.status!=MatchStatus.PLAYED){{manage=match}}else null) } } }
                }
            }
        }
    },confirmButton={TextButton(close){Text("Cerrar")}})
    if(register) TeamFormDialog({register=false}){vm.registerTeam(id,it);register=false;vm.loadTeams(id);vm.loadTournament(id)}
    teamDetail?.let{team->TeamDetailDialog(team){teamDetail=null}}
    if(confirmStart) ConfirmDialog("¿Iniciar torneo?","Se generará el cuadro y ya no se admitirán equipos.","Iniciar",{confirmStart=false}){vm.startTournament(id);vm.loadTournament(id);confirmStart=false}
    manage?.let { match -> MatchManageDialog(match,{manage=null}) { date,home,away -> if(date!=null)vm.scheduleMatch(id,match.id,date) else vm.scoreMatch(id,match.id,home!!,away!!);manage=null } }
}
@Composable private fun TeamDetailDialog(t:TeamResponse,close:()->Unit){AlertDialog(onDismissRequest=close,title={Text(t.name)},text={Column(verticalArrangement=Arrangement.spacedBy(7.dp)){StatusChip(if(t.stats.eliminated)"Eliminado" else "En competencia",!t.stats.eliminated);Text("Contacto",style=MaterialTheme.typography.titleMedium);Text(t.contactName);Text(t.contactEmail);Text(t.contactPhone);HorizontalDivider();Text("Estadísticas",style=MaterialTheme.typography.titleMedium);InfoLine("Partidos jugados",t.stats.matchesPlayed.toString());InfoLine("Victorias",t.stats.matchesWon.toString());InfoLine("Derrotas",t.stats.matchesLost.toString());InfoLine("Puntos a favor",t.stats.pointsFor.toString());InfoLine("Puntos en contra",t.stats.pointsAgainst.toString())}},confirmButton={TextButton(close){Text("Cerrar")}})}
@Composable private fun TeamFormDialog(close:()->Unit,save:(RegisterTeamRequest)->Unit){var n by remember{mutableStateOf("")};var c by remember{mutableStateOf("")};var e by remember{mutableStateOf("")};var p by remember{mutableStateOf("")};var error by remember{mutableStateOf<String?>(null)};AlertDialog(onDismissRequest=close,title={Text("Inscribir equipo")},text={Column(Modifier.verticalScroll(rememberScrollState())){Field(n,{n=it},"Nombre del equipo",error?.takeIf{n.isBlank()});Field(c,{c=it},"Responsable",error?.takeIf{c.isBlank()});Field(e,{e=it},"Correo",error?.takeIf{e.isBlank()});Field(p,{p=it},"Teléfono",error?.takeIf{p.isBlank()})}},confirmButton={Button({error=Validators.team(n,c,e,p);if(error==null)save(RegisterTeamRequest(n,c,e,p))}){Text("Inscribir equipo")}},dismissButton={TextButton(close){Text("Cancelar")}})}
@Composable private fun TournamentFormDialog(close:()->Unit,save:(CreateTournamentRequest)->Unit){var n by remember{mutableStateOf("")};var teams by remember{mutableStateOf("4")};var prize by remember{mutableStateOf("")};var error by remember{mutableStateOf<String?>(null)};AlertDialog(onDismissRequest=close,title={Text("Crear torneo")},text={Column{Field(n,{n=it},"Nombre",error?.takeIf{n.isBlank()});Field(teams,{teams=it},"Máximo de equipos",error?.takeIf{teams.toIntOrNull()==null});Field(prize,{prize=it},"Premio (opcional)");Text("Deporte: Básquet")}},confirmButton={Button({error=Validators.tournament(n,teams.toIntOrNull());if(error==null)save(CreateTournamentRequest(n,SportType.BASKET,teams.toInt(),prize.ifBlank{null}))}){Text("Crear torneo")}},dismissButton={TextButton(close){Text("Cancelar")}})}
@Composable private fun MatchManageDialog(m:MatchResponse,close:()->Unit,save:(String?,Int?,Int?)->Unit){if(m.status==MatchStatus.PENDING){var date by remember{mutableStateOf<LocalDate?>(null)};var time by remember{mutableStateOf<LocalTime?>(null)};var sd by remember{mutableStateOf(false)};var st by remember{mutableStateOf(false)};AlertDialog(onDismissRequest=close,title={Text("Programar partido")},text={Column(horizontalAlignment=Alignment.CenterHorizontally){Text("${m.homeTeamName?:"Por definir"} vs ${m.awayTeamName?:"Por definir"}");OutlinedButton({sd=true},Modifier.fillMaxWidth()){Text(date?.toString()?:"Seleccionar fecha")};OutlinedButton({st=true},Modifier.fillMaxWidth()){Text(time?.toString()?:"Seleccionar hora")}}},confirmButton={Button({if(date!=null&&time!=null)save(LocalDateTime.of(date,time).toString(),null,null)},enabled=date!=null&&time!=null){Text("Programar")}},dismissButton={TextButton(close){Text("Cancelar")}});if(sd)DatePickerModal({sd=false}){date=it};if(st)TimePickerModal({st=false}){time=it}}else ScoreDialog(m,close,save)}
@Composable private fun ScoreDialog(m:MatchResponse,close:()->Unit,save:(String?,Int?,Int?)->Unit){var h by remember{mutableStateOf("")};var a by remember{mutableStateOf("")};var error by remember{mutableStateOf<String?>(null)};var confirm by remember{mutableStateOf(false)};AlertDialog(onDismissRequest=close,title={Text("Registrar resultado")},text={Column{Field(h,{h=it},m.homeTeamName?:"Local",error);Field(a,{a=it},m.awayTeamName?:"Visitante",error)}},confirmButton={Button({error=Validators.score(h.toIntOrNull(),a.toIntOrNull());if(error==null)confirm=true}){Text("Guardar resultado")}},dismissButton={TextButton(close){Text("Cancelar")}});if(confirm)ConfirmDialog("Confirmar marcador","${m.homeTeamName}: $h\n${m.awayTeamName}: $a","Guardar",{confirm=false}){save(null,h.toInt(),a.toInt());confirm=false}} 

@Composable fun ProfileScreen(vm:ContentViewModel,role:UserRole,onLogout:()->Unit){val state by vm.profile.collectAsState();var edit by remember{mutableStateOf(false)};var logout by remember{mutableStateOf(false)};LaunchedEffect(Unit){vm.loadProfile()};StateView(state,onRetry={vm.loadProfile()}){p->Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(24.dp),horizontalAlignment=Alignment.CenterHorizontally){Surface(shape=MaterialTheme.shapes.large,color=MaterialTheme.colorScheme.primaryContainer){Icon(Icons.Default.Person,null,Modifier.padding(24.dp).size(60.dp),tint=MaterialTheme.colorScheme.primary)};Text(p.name,style=MaterialTheme.typography.headlineMedium,modifier=Modifier.padding(top=14.dp));StatusChip(role.name);Card(Modifier.fillMaxWidth().padding(vertical=20.dp)){Column(Modifier.padding(18.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){InfoLine("Correo",p.email?:"Sin correo");InfoLine("Teléfono",p.phone?:"Sin teléfono")}};PrimaryButton("Editar perfil",{edit=true});OutlinedButton({logout=true},Modifier.fillMaxWidth().padding(top=10.dp)){Icon(Icons.Default.Logout,null);Text(" Cerrar sesión")};if(edit)ProfileFormDialog(p,{edit=false}){vm.saveProfile(it,false);edit=false}}};if(logout)ConfirmDialog("¿Cerrar sesión?","Tendrás que volver a ingresar tus credenciales.","Cerrar sesión",{logout=false}){onLogout();logout=false}}
@Composable private fun ProfileFormDialog(p:UserResponse,close:()->Unit,save:(UserRequest)->Unit){var n by remember{mutableStateOf(p.name)};var e by remember{mutableStateOf(p.email?:"")};var ph by remember{mutableStateOf(p.phone?:"")};var error by remember{mutableStateOf<String?>(null)};AlertDialog(onDismissRequest=close,title={Text("Editar perfil")},text={Column{Field(n,{n=it},"Nombre",error?.takeIf{n.isBlank()});Field(e,{e=it},"Correo",error?.takeIf{e.isNotBlank()&&!e.contains('@')});Field(ph,{ph=it},"Teléfono",error?.takeIf{ph.isNotBlank()&&ph.length<7})}},confirmButton={Button({error=Validators.profile(n,e,ph);if(error==null)save(UserRequest(n,e.ifBlank{null},ph.ifBlank{null}))}){Text("Guardar cambios")}},dismissButton={TextButton(close){Text("Cancelar")}})}
